/*
 * This source file was generated by the Gradle 'init' task
 */
package eu.nebulouscloud.optimiser.twin;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.URISyntaxException;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

class AppTest {

    private static final ObjectMapper mapper = new ObjectMapper();

    // A temporary current directory for ABS databases
    @TempDir Path tempDir;

    @Test void parseDSLMessage() throws IOException, URISyntaxException {
        URL resourceURL = AppTest.class.getClassLoader().getResource("app-creation-message.json");
        JsonNode dslMessage = mapper.readTree(resourceURL.openStream());
        NebulousApp app = NebulousApp.fromAppMessage(dslMessage);
        assertNotNull(app);
        String uuid = app.getUuid();
        assertNotNull(NebulousApp.fromUuid(uuid));
    }

    @Test
    void runSimpleSimulation() throws Exception {
        URL traceDbURL = AppTest.class.getClassLoader().getResource("simple-execution/trace.db");
        URL scenarioDbURL = AppTest.class.getClassLoader().getResource("simple-execution/scenario.db");
        URL calibrationDbURL = AppTest.class.getClassLoader().getResource("simple-execution/calibration.db");
        Path traceDb = tempDir.resolve("trace.db");
        Path scenarioDb = tempDir.resolve("scenario.db");
        Path calibrationDb = tempDir.resolve("calibration.db");
        Files.copy(traceDbURL.openStream(), traceDb);
        Files.copy(scenarioDbURL.openStream(), scenarioDb);
        Files.copy(calibrationDbURL.openStream(), calibrationDb);
        long nEvents = -1;
        try (Connection connection = DriverManager.getConnection("jdbc:sqlite:" + traceDb.toString());
             Statement statement = connection.createStatement()) {
            ResultSet result = statement.executeQuery(
                "SELECT COUNT(*) FROM trace_events");
            assertTrue(result.next());
            nEvents = result.getLong(1);
            assertFalse(result.next());
        }
        String simulationResult = Simulator.simulate(traceDb, scenarioDb, calibrationDb);
        assertEquals(nEvents, simulationResult.lines().count());
    }

    @Test void invalidSolverSolution() throws IOException {
        URL resourceURL = AppTest.class.getClassLoader().getResource("app-creation-message.json");
        JsonNode dslMessage = mapper.readTree(resourceURL.openStream());
        NebulousApp app = NebulousApp.fromAppMessage(dslMessage);
        assertNotNull(app);
        URL solutionURL = AppTest.class.getClassLoader().getResource("sample-solution-missing-app-id.json");
        JsonNode solutionMessage = mapper.readTree(solutionURL.openStream());
        assertFalse(DeploymentImporter.saveSolverSolution(Path.of("config.db"), app, solutionMessage));
    }

    @Test void createScenarioFromDSLandSolverMessage() throws IOException, SQLException {
        Path db = Path.of(tempDir.toString(), "config.db");
        URL resourceURL = AppTest.class.getClassLoader().getResource("app-creation-message.json");
        JsonNode dslMessage = mapper.readTree(resourceURL.openStream());
        NebulousApp app = NebulousApp.fromAppMessage(dslMessage);
        assertNotNull(app);
        URL solutionURL = AppTest.class.getClassLoader().getResource("sample-solution.json");
        JsonNode solutionMessage = mapper.readTree(solutionURL.openStream());
        assertTrue(DeploymentImporter.saveSolverSolution(db, app, solutionMessage));
        try (Connection connection = DriverManager.getConnection("jdbc:sqlite:" + db.toString());
             Statement statement = connection.createStatement()) {
            ResultSet result = statement.executeQuery(
                "SELECT * FROM scenario WHERE component = 'license-plate-reading-service'");
            assertTrue(result.next());
            assertEquals("license-plate-reading-service", result.getString(1)); // component
            assertEquals(4, result.getInt(2));    // cpu
            assertEquals(4096, result.getInt(3)); // memory
            assertEquals(8, result.getInt(4));    // replicas
            assertFalse(result.next());
        }
    }

    @Test void createScenarioFromDSLMessage() throws IOException, SQLException {
        Path db = Path.of(tempDir.toString(), "config.db");
        URL resourceURL = AppTest.class.getClassLoader().getResource("app-creation-message.json");
        JsonNode dslMessage = mapper.readTree(resourceURL.openStream());
        NebulousApp app = NebulousApp.fromAppMessage(dslMessage);
        assertNotNull(app);
        assertTrue(DeploymentImporter.saveSolverSolution(db, app, null));
        try (Connection connection = DriverManager.getConnection("jdbc:sqlite:" + db.toString());
             Statement statement = connection.createStatement()) {
            ResultSet result = statement.executeQuery(
                "SELECT component, cpu, memory, replicas FROM scenario WHERE component = 'license-plate-reading-service'");
            assertTrue(result.next());
            assertEquals("license-plate-reading-service", result.getString(1)); // component
            assertEquals(2, result.getInt(2));    // cpu
            assertEquals(1024, result.getInt(3)); // memory
            assertEquals(1, result.getInt(4));    // replicas
            assertFalse(result.next());
        }
    }

    @Test void createScenarioFromCsv() throws SQLException {
        String csv = """
            Component,Replicas,Cores,Memory
            firecoat-sensor,1,1,512
            firecoat-persist,2,4,2048
            firecoat-postgis,1,2,4096
            """;
        Path db = Path.of(tempDir.toString(), "config.db");
        assertTrue(DeploymentImporter.saveCsvScenario(db, csv));
        try (Connection connection = DriverManager.getConnection("jdbc:sqlite:" + db.toString());
             Statement statement = connection.createStatement()) {
            ResultSet result = statement.executeQuery(
                "SELECT component, cpu, memory, replicas FROM scenario ORDER BY component");
            assertTrue(result.next());
            assertEquals("firecoat-persist", result.getString(1)); // component
            assertEquals(4, result.getInt(2));                     // cpu
            assertEquals(2048, result.getInt(3));                  // memory
            assertEquals(2, result.getInt(4));                     // replicas
            assertTrue(result.next());
            assertEquals("firecoat-postgis", result.getString(1)); // component
            assertEquals(2, result.getInt(2));                     // cpu
            assertEquals(4096, result.getInt(3));                  // memory
            assertEquals(1, result.getInt(4));                     // replicas
            assertTrue(result.next());
            assertEquals("firecoat-sensor", result.getString(1)); // component
            assertEquals(1, result.getInt(2));                     // cpu
            assertEquals(512, result.getInt(3));                   // memory
            assertEquals(1, result.getInt(4));                     // replicas
            assertFalse(result.next());
        }
    }

    @Test void createCalibrationDatabase() throws SQLException {
        Path db = Path.of(tempDir.toString(), "calibration.db");
        String csv = """
            license-plate-reading-service,2.5,3
            """;
        assertTrue(CalibrationImporter.saveCalibration(db, csv));
        try (Connection connection = DriverManager.getConnection("jdbc:sqlite:" + db.toString());
             Statement statement = connection.createStatement()) {
            ResultSet result = statement.executeQuery(
                "SELECT * FROM factors");
            assertTrue(result.next());
            assertEquals("license-plate-reading-service", result.getString(1)); // component
            assertEquals(2.5, result.getDouble(2));    // constant factor
            assertEquals(3, result.getDouble(3)); // variable factor
            assertFalse(result.next());
        }
    }

    @Test void readTrace() throws IOException, SQLException {
        Path db = Path.of(tempDir.toString(), "traces.db");
        URL traceURL = AppTest.class.getClassLoader().getResource("logs.jsonl");
        BufferedReader reader = new BufferedReader(
            new InputStreamReader(traceURL.openStream(), StandardCharsets.UTF_8));
        long nTraces = TraceImporter.storeLog(db, reader);
        assertEquals(48, nTraces);
        try (Connection connection = DriverManager.getConnection("jdbc:sqlite:" + db.toString());
             Statement statement = connection.createStatement()) {
            ResultSet result = statement.executeQuery(
                "SELECT COUNT(*) FROM trace_events");
            assertTrue(result.next());
            assertEquals(48, result.getLong(1));
            assertFalse(result.next());
        }
    }

}
